package com.connectx.group.service;

import com.connectx.common.exception.ApiException;
import com.connectx.conversation.dto.ConversationMemberDto;
import com.connectx.conversation.entity.Conversation;
import com.connectx.conversation.entity.ConversationMember;
import com.connectx.conversation.entity.ConversationType;
import com.connectx.conversation.entity.GroupRole;
import com.connectx.conversation.repository.ConversationMemberRepository;
import com.connectx.conversation.repository.ConversationRepository;
import com.connectx.group.dto.CreateGroupRequestDto;
import com.connectx.group.dto.GroupDto;
import com.connectx.group.entity.ChatGroup;
import com.connectx.group.repository.ChatGroupRepository;
import com.connectx.user.entity.User;
import com.connectx.user.repository.UserRepository;
import com.connectx.user.service.ProfileVisibilityService;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Isolation;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * Groups Stage 1 backend foundation. A GROUP is a Conversation (type=GROUP) + a ChatGroup row +
 * ConversationMember rows with a role -- deliberately not a parallel hierarchy, so every other
 * conversation-scoped mechanism (messaging, WebSocket topic authorization from Stage 0, pin/mute/
 * archive) keeps working against a group's conversationId without modification.
 * <p>
 * ConversationService remains responsible for generic, DIRECT-or-GROUP-agnostic conversation
 * operations; this service owns everything group-specific (creation, role assignment, membership
 * limits) so ConversationService doesn't need to grow group-shaped branches.
 */
@Service
public class GroupService {

    private final ConversationRepository conversationRepository;
    private final ConversationMemberRepository conversationMemberRepository;
    private final ChatGroupRepository chatGroupRepository;
    private final UserRepository userRepository;
    private final ProfileVisibilityService profileVisibilityService;
    private final GroupAuthorizationService groupAuthorizationService;

    public GroupService(ConversationRepository conversationRepository,
                         ConversationMemberRepository conversationMemberRepository,
                         ChatGroupRepository chatGroupRepository,
                         UserRepository userRepository,
                         ProfileVisibilityService profileVisibilityService,
                         GroupAuthorizationService groupAuthorizationService) {
        this.conversationRepository = conversationRepository;
        this.conversationMemberRepository = conversationMemberRepository;
        this.chatGroupRepository = chatGroupRepository;
        this.userRepository = userRepository;
        this.profileVisibilityService = profileVisibilityService;
        this.groupAuthorizationService = groupAuthorizationService;
    }

    @Transactional
    public GroupDto createGroup(Long currentUserId, CreateGroupRequestDto dto) {
        String name = validateName(dto.getName());
        String description = validateDescription(dto.getDescription());

        // The authenticated caller is always the creator/owner -- CreateGroupRequestDto has no
        // creatorUserId or role field, so there is nothing here for a client to forge either with.
        User creator = userRepository.findById(currentUserId)
                .orElseThrow(() -> new ApiException(HttpStatus.NOT_FOUND, "USER_NOT_FOUND", "Current user not found"));

        Conversation conversation = conversationRepository.save(new Conversation(ConversationType.GROUP));

        ChatGroup chatGroup = new ChatGroup(conversation, name, description, creator);
        chatGroup = chatGroupRepository.save(chatGroup);

        // Self-invocation, so addMember's own @Transactional(isolation=READ_COMMITTED) does not
        // apply here via AOP -- this runs at whatever isolation createGroup's own @Transactional
        // uses instead (MySQL's default REPEATABLE READ). That's fine specifically for this call:
        // conversationId was just generated by this same transaction, so no other transaction can
        // possibly reference it yet -- there is no concurrent writer for the isolation level to
        // protect against here. The pessimistic lock inside addMember still executes correctly
        // regardless (it goes through ChatGroupRepository's own proxy, not this class's), it's
        // only the isolation-level override that's skipped. GroupInvitationService's calls into
        // this same 5-arg overload are genuine cross-bean calls where the annotation does apply,
        // which is the path that actually needs it (see that method's javadoc).
        ConversationMember ownerMembership = addMember(conversation, creator, GroupRole.OWNER, null, false);
        conversation.getMembers().add(ownerMembership);

        return buildGroupDto(conversation, chatGroup, 1L, GroupRole.OWNER);
    }

    @Transactional(readOnly = true)
    public GroupDto getGroupDetails(Long currentUserId, Long groupId) {
        ChatGroup chatGroup = groupAuthorizationService.requireActiveMember(currentUserId, groupId);
        long activeMemberCount = conversationMemberRepository.countByConversationIdAndDeletedAtIsNull(groupId);
        GroupRole viewerRole = conversationMemberRepository.findByConversationIdAndUserId(groupId, currentUserId)
                .map(ConversationMember::getRole)
                .orElse(null);
        return buildGroupDto(chatGroup.getConversation(), chatGroup, activeMemberCount, viewerRole);
    }

    @Transactional(readOnly = true)
    public List<ConversationMemberDto> getGroupMembers(Long currentUserId, Long groupId) {
        groupAuthorizationService.requireActiveMember(currentUserId, groupId);

        List<ConversationMember> members = conversationMemberRepository
                .findByConversationIdAndDeletedAtIsNullWithUsers(groupId);
        List<User> memberUsers = members.stream().map(ConversationMember::getUser).collect(Collectors.toList());
        Map<Long, Boolean> photoVisibilityByUserId = profileVisibilityService.resolvePhotoVisibility(currentUserId, memberUsers);

        return members.stream()
                .map(m -> ConversationMemberDto.fromEntity(m, photoVisibilityByUserId.getOrDefault(m.getUser().getId(), false)))
                .collect(Collectors.toList());
    }

    /**
     * Adds a brand-new active membership row for {@code user} in {@code conversation}, under the
     * central {@link GroupAuthorizationService#MAX_ACTIVE_GROUP_MEMBERS} cap. Rejects an existing
     * soft-deleted (INACTIVE) row rather than restoring it -- see the 5-arg overload's javadoc for
     * when restoration is allowed instead. Convenience overload for every call site that must
     * never restore (group creation; the DIRECT_ADD outcome of a fresh invitation, which by
     * construction only ever targets a NEVER_MEMBER user -- see GroupAuthorizationService#evaluateAddMember).
     * <p>
     * Carries its own {@code @Transactional} (matching the 5-arg overload's) rather than relying
     * on the 5-arg call below to establish one: that call is a same-class self-invocation, which
     * bypasses Spring's AOP proxy entirely, so the 5-arg method's annotation would silently not
     * apply if THIS method were the caller's actual entry point (e.g. a test calling this overload
     * directly with no transaction of its own already open) -- without an annotation here too, the
     * pessimistic lock inside the 5-arg method would be acquired and released within its own
     * separate implicit transaction before the count-check and insert even ran, providing no
     * protection at all.
     */
    @Transactional(isolation = Isolation.READ_COMMITTED)
    public ConversationMember addMember(Conversation conversation, User user, GroupRole role, Long invitedByUserId) {
        return addMember(conversation, user, role, invitedByUserId, false);
    }

    /**
     * Groups Stage 2: the one race-safe primitive every membership-creating path (group creation,
     * a fresh invitation's DIRECT_ADD outcome, and GroupInvitationService#acceptInvitation) must go
     * through -- centralizing the limit/duplicate/reactivation enforcement here rather than
     * re-deriving it per call site.
     * <p>
     * {@code allowRestoreInactive} governs Stage 1.5's consent rule: a previously LEFT/REMOVED
     * (collapsed as INACTIVE -- see GroupAuthorizationService's class-level javadoc) member must
     * never be silently reactivated. {@code false} (the 4-arg overload) enforces that by rejecting
     * an INACTIVE target outright. {@code true} is reserved for the one path where the user has
     * just given exactly that consent explicitly -- accepting a fresh invitation -- and reuses
     * their existing row (deletedAt -> null) instead of inserting a duplicate
     * (conversation_id, user_id) pair, which uk_convmember_conversation_user
     * (V3__group_membership_unique_constraint.sql) would reject anyway.
     * <p>
     * <b>Race safety.</b> {@link ChatGroupRepository#findByIdForUpdate} takes a pessimistic write
     * lock on the group's chat_groups row first, before the active-member-count check, and holds
     * it for the rest of the caller's transaction (this method does not use REQUIRES_NEW -- unlike
     * ConnectionService's insert-and-recover pattern, the caller here needs this insert atomic
     * with its own surrounding writes, e.g. GroupInvitationService#acceptInvitation marking the
     * invitation ACCEPTED in the same transaction). That serializes every concurrent call to this
     * method for the SAME group (direct-add, accept, another accept) into a queue: whichever
     * transaction acquires the lock first re-reads the count and target state under it, so a
     * second, now-unblocked caller always sees the first's effects and is correctly rejected
     * (ALREADY_GROUP_MEMBER or GROUP_MEMBER_LIMIT_EXCEEDED) rather than double-inserting or
     * overshooting the cap. READ_COMMITTED (not MySQL's default REPEATABLE READ) for the same
     * reason ConversationService#createOrGetDirectConversation uses it: a plain-snapshot read taken
     * before the lock wait would miss the unblocking transaction's just-committed state. The
     * DataIntegrityViolationException catch below is a defense-in-depth backstop against the DB
     * constraint, not the primary race guard -- the lock is.
     */
    @Transactional(isolation = Isolation.READ_COMMITTED)
    public ConversationMember addMember(Conversation conversation, User user, GroupRole role, Long invitedByUserId,
                                         boolean allowRestoreInactive) {
        Long conversationId = conversation.getId();

        chatGroupRepository.findByIdForUpdate(conversationId)
                .orElseThrow(() -> new ApiException(HttpStatus.NOT_FOUND, "GROUP_NOT_FOUND", "Group not found"));

        GroupAuthorizationService.MembershipState state = groupAuthorizationService.resolveMembershipState(conversationId, user.getId());
        if (state == GroupAuthorizationService.MembershipState.ACTIVE_MEMBER) {
            throw new ApiException(HttpStatus.CONFLICT, "ALREADY_GROUP_MEMBER", "User is already a member of this group");
        }
        if (state == GroupAuthorizationService.MembershipState.INACTIVE && !allowRestoreInactive) {
            throw new ApiException(HttpStatus.CONFLICT, "GROUP_REINVITATION_REQUIRED",
                    "This user previously left or was removed from the group and must be re-invited");
        }

        long activeCount = conversationMemberRepository.countByConversationIdAndDeletedAtIsNull(conversationId);
        if (activeCount >= GroupAuthorizationService.MAX_ACTIVE_GROUP_MEMBERS) {
            throw new ApiException(HttpStatus.CONFLICT, "GROUP_MEMBER_LIMIT_EXCEEDED",
                    "This group has reached the maximum of " + GroupAuthorizationService.MAX_ACTIVE_GROUP_MEMBERS + " members");
        }

        if (state == GroupAuthorizationService.MembershipState.INACTIVE) {
            ConversationMember restored = conversationMemberRepository.findByConversationIdAndUserId(conversationId, user.getId())
                    .orElseThrow();
            restored.setDeletedAt(null);
            restored.setRole(role);
            restored.setInvitedByUserId(invitedByUserId);
            return conversationMemberRepository.save(restored);
        }

        ConversationMember member = new ConversationMember(conversation, user);
        member.setRole(role);
        member.setInvitedByUserId(invitedByUserId);
        try {
            return conversationMemberRepository.saveAndFlush(member);
        } catch (DataIntegrityViolationException e) {
            throw new ApiException(HttpStatus.CONFLICT, "ALREADY_GROUP_MEMBER", "User is already a member of this group");
        }
    }

    private GroupDto buildGroupDto(Conversation conversation, ChatGroup chatGroup, long activeMemberCount, GroupRole viewerRole) {
        GroupDto dto = new GroupDto();
        dto.setId(conversation.getId());
        dto.setType(conversation.getType().name());
        dto.setName(chatGroup.getName());
        dto.setDescription(chatGroup.getDescription());
        dto.setAvatarUrl(chatGroup.getAvatarUrl());
        dto.setWhoCanInvite(chatGroup.getWhoCanInvite().name());
        dto.setCreatedByUserId(chatGroup.getCreatedByUser().getId());
        dto.setCurrentUserRole(viewerRole != null ? viewerRole.name() : null);
        dto.setActiveMemberCount(activeMemberCount);
        dto.setCreatedAt(chatGroup.getCreatedAt());
        dto.setUpdatedAt(chatGroup.getUpdatedAt());
        return dto;
    }

    private String validateName(String rawName) {
        String name = rawName != null ? rawName.trim() : "";
        if (name.isEmpty()) {
            throw new ApiException(HttpStatus.BAD_REQUEST, "GROUP_NAME_REQUIRED", "Group name is required");
        }
        if (name.length() > 100) {
            throw new ApiException(HttpStatus.BAD_REQUEST, "GROUP_NAME_TOO_LONG", "Group name must be 100 characters or fewer");
        }
        return name;
    }

    private String validateDescription(String rawDescription) {
        if (rawDescription == null) {
            return null;
        }
        String description = rawDescription.trim();
        if (description.isEmpty()) {
            return null;
        }
        if (description.length() > 500) {
            throw new ApiException(HttpStatus.BAD_REQUEST, "GROUP_DESCRIPTION_TOO_LONG", "Group description must be 500 characters or fewer");
        }
        return description;
    }
}
